AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BuildId:
    Type: Number
    Description: The BuildId of the code being deployed
Description: bumblebee-api
Resources:

  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: S3ReadPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource:
                - 'arn:aws:s3:::secrets-sasirekha3/bumblebee-api*'
        - PolicyName: CloudwatchLogPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:*'
                Resource:
                  - '*'
        - PolicyName: ESGetPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'es:*'
                Resource:
                  - '*'
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:*'
                Resource:
                  - '*'
      RoleName: api-pdiot-role

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: api-pdiot
        S3Key: !Join [ "/", [ !Ref BuildId, "lambda.zip" ] ]
      FunctionName: api-pdiot
      Handler: lambda.handler
      PackageType: Zip
      Role: !GetAtt MyLambdaRole.Arn
      Runtime: nodejs12.x
      Timeout: 300